name: Test Workflow

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run script
        run: ./script.sh 

      - name: Run Test
        run: |
          message="$(git log --pretty=%s)"
          IFS=$'\n'
          for item in $message; do
            number=$(grep -oP '\(#\K\d+(?=\))' <<< "$item" | rev | cut -d' ' -f1 | rev || true)
            if [ -n "$number" ]; then
              echo "$number"
            else
              echo "No number found in '$item'"
            fi
          done
    
    

