name: Test Workflow

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run script
        run: ./script.sh 

      - name: Run Test
        run: |
          message="foo(#1234) bar foo"
          for item in $message ; do
            number=$(echo "$item" | grep -oP '\(#\K\d+(?=\))')
            echo "$number"
          done
          echo "aled"
