name: Test Workflow

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run script
        run: ./script.sh 

      - name: Run Test
        run: |
          message="foo(#1234) bar foo"
          IFS=' ' read -r -a words <<< "$message"
          for item in "${words[@]}"; do
            number=$(echo "$item" | grep -oP '\(#\K\d+(?=\))' || true)
            if [ -n "$number" ]; then
              echo "$number"
            else
              echo "No number found in '$item'"
            fi
          done
          echo "aled"



